### PR TITLE
A rewrite of the namegame bot, integrated into Dozer

### PR DESCRIPTION
**Pull request by guineawheek**
This is a mostly complete reimplementation of Devin's original namebot. 

Featuring:
 * Separate timer event loop with game state locks to try to avoid game state corruption and crashes
 * FRC and FTC support
 * More embeds that count down 

Not featuring:
 * Any sort of database stuff yet (leaderboard, config options)

### CODE REVIEW

**Comment by bkeeneykid** [comment]
Oof, hits me right in the heart.

**Comment by bkeeneykid** [comment]
Side note - in my somewhat planned rewrite i was planning to change it to generate async events every time rather than this one big loop, but this still works. Review (prepare for me to be harsh on my own code) incoming.

**Comment by guineawheek** [comment]
Obsoleated by #66

**Comment by guineawheek** [comment]
Reopening to replace #66

**Comment by guineawheek** [comment]
This should address Ian’s concerns in #66 and then some.

**Comment by tweirtx** [comment]
[NameGame](https://trello.com/c/htukOrTU/62-namegame)

**Comment by tweirtx** [comment]
I hate LZMA but I'll allow it

**Pull request merged**
