### PR TITLE
Member and message logging

### PR DESCRIPTION
**Pull request by tweirtx**
I've got member and message logging working, mutes come after this is finalized and I learn how to do perms overrides.

### CODE REVIEW

**Comment by mcao** [comment]
One thing - accounting for messages above 1000 characters. And it looks like there's a conflict...

**Comment by tweirtx** [comment]
@endreman0 length checking is now in place.

**Comment by tweirtx** [comment]
Current status: This hasn't been abandoned, I'm nearly done except there's one issue I need to fix and I'm swamped with schoolwork right now. Will fix if I get free time to do so

**Comment by tweirtx** [comment]
I'll fix that in the next release, I'm trying to get this merged now so that member logging works on Dozer again

**Comment by tweirtx** [comment]
Should be good to go now

**Comment by tweirtx** [comment]
I've pulled the latest code from the repo, and I've had my PR open for longer. If anything they should have checked my PR first

**Comment by tweirtx** [comment]
Sorry about that, I'm not in the best mood today and I'm just frustrated that every time I submit something I get rejected

**Pull request merged**
