### PR TITLE
Should fix when teams don't have a website in TBA, fixes #403

### LINKED ISSUE #403: {bug} TBA gives HTTP Exception when trying to pull data for certain teams
image
Example of the issue being experienced.  So far I have only noticed the issue on team 2338, which is linked [here](https://www.thebluealliance.com/team/2338).  Not sure what is causing the error, but I have tested with various other teams and have not encountered the same problem in the team number I tested.

### PR DESCRIPTION
**Pull request by BCurbs**
Basically the title.

### CODE REVIEW

**Comment by WaterGame2023** [comment]
I assume you tested it with the same team I was having issues with?

**Comment by BCurbs** [comment]
Yep just shown as fixed in the development discord server on my copy of dozer.

**Review by devyntk — APPROVED** [review]

**Review by WaterGame2023 — APPROVED** [review]
Sending a prayer to the api gods please work

**Comment by WaterGame2023** [comment]
Wait in the discord it worked one time but not the other

**Comment by BCurbs** [comment]
I dont know it won't let me request review from both, sorry for the notifications.

**Review by WaterGame2023 — APPROVED** [review]
Looks good

**Pull request merged**
