### PR TITLE
Implement the voicebind command and automatic role giving/taking

### PR DESCRIPTION
**Pull request by guineawheek**
yay got around to the db stuff (finally).

Seems to be fully working atm.

### CODE REVIEW

**Comment by mcao** [comment]
Have you accounted for moving from one voice channel to another?

**Comment by guineawheek** [comment]
Fixed the switching between channels thing, oops.

Also updated for Devin's suggestion as well

**Comment by guineawheek** [comment]
That's why there's a check to make sure that the channels between the
before and after states are actually different as well

**Comment by tweirtx** [comment]
[Voice text channel handling](https://trello.com/c/Vz8N57Bc/36-voice-text-channel-handling)

**Comment by guineawheek** [comment]
Alrighty, I added in some docs for `voicebindlist`

**Pull request merged**
