### PR TITLE
Automatic team number appending to nickname on join

### PR DESCRIPTION
**Pull request by tweirtx**
This will append a team number to a user's nickname when they join if they have exactly 1 team association in the database.

### CODE REVIEW

**Comment by tweirtx** [comment]
[Automatic nickname setting on entry verification w/ team num](https://trello.com/c/oeYFkknv/13-automatic-nickname-setting-on-entry-verification-w-team-num)

**Comment by WardBenjamin** [comment]
Just as a note, `query.first()` can be MASSIVELY faster than `query.all()` because the SQL statement immediately exits when it finds a match rather than searching the database. (It's an identical speed if there's no row that matches, but otherwise it'll improve speeds in almost all cases.)

**Comment by tweirtx** [comment]
I could have sworn I changed that, let me look into it

**Comment by tweirtx** [comment]
As well as the nickname thing

**Pull request merged**
