### PR TITLE
TBA raw patch and TBA link added

### PR DESCRIPTION
**Pull request by 770352**
Fixed &tba raw, Added &tba sponsors, Added TBA Link to &tba team for mobile users.

### CODE REVIEW

**Comment by 770352** [comment]
This PR also fixes Issue #58

**Comment by 770352** [comment]
Pulling sponsors command to get the fix pushed sooner.

**Comment by tweirtx** [comment]
Don't merge this PR, it explicitly undoes my bug fixes

**Comment by 770352** [comment]
@tweirtx Should be ok now.

**Comment by 770352** [comment]
Also to clarify the reason to add the TBA Link to the TBA Team command, Discord for Android and I'm guessing iOS too, I found out that Discord does not turn the title into a link for some dumb reason but does turn the added TBA Link into a clickable link. If there is a better way to fix this, Please let me know.

**Pull request merged**
