### PR TITLE
Made the invite command

### PR DESCRIPTION
**Pull request by 770352**

### CODE REVIEW

**Comment by 770352** [comment]
Nah Fam, Thats too easy.

**Comment by 770352** [comment]
Should be all fixed.

**Comment by 770352** [comment]
Or, I can just hard code it and it will be fine. Quit over complicating things.

**Comment by endreman0** [comment]
Overcomplicating things is leaving the bot's permissions as a hardcoded number, and generating more work down the line. Whenever we add a command, in this case, we have to find the numeric value of every permission the command needs and make sure it is included in that number, which is tedious and error-prone. Hard-coding will not be fine.

**Comment by tweirtx** [comment]
I have been told by Harold that he has abandoned this command. Closing PR.

**Pull request closed without merging**
