### PR TITLE
Mutes, deafens, and member logs now include member counting. 

### PR DESCRIPTION
**Pull request by tweirtx**

### CODE REVIEW

**Comment by tweirtx** [comment]
Yes, I'm aware that weird file changes are happening. Turns out I did a bad when updating my branch.

**Comment by tweirtx** [comment]
Fixed merge conflicts

**Comment by tweirtx** [comment]
I'm working on updating, will test when I have the chance

**Comment by tweirtx** [comment]
It kinda works but at the same time kinda doesn't

**Comment by tweirtx** [comment]
I'm close to making it work I think, one error to fix and then good to go

**Comment by tweirtx** [comment]
Aaaaaaack

**Comment by tweirtx** [comment]
I'll have to see but this may be my last development contribution before having to go dark for a while. Hopefully not but there is a chance

**Comment by guineawheek** [comment]
Interesting whitespace policy of your IDE. Anyway, seems fine. Must've been a mountain of work - at least now I won't have to manually edit people's perms to mute them. I am going to miss how excited Dozer is to give roles but for the sake of getting this PR merged don't bother

**Comment by tweirtx** [comment]
Oops, accidentally dismissed your reviews

**Comment by tweirtx** [comment]
True, since the change was literally one punctuation point in a string I'm just going to merge

**Comment by tweirtx** [comment]
[Mutes and Deafens](https://trello.com/c/jvNveU3J/48-mutes-and-deafens)

**Pull request merged**
