### PR TITLE
Create ftcqa.py

### PR DESCRIPTION
**Pull request by skruglov2023**
Added the FTC Q/A forum cog from old dozer, with the dozer2.0 updates.

### CODE REVIEW

**Comment by devyntk** [comment]
Dozer as a bot isn't FTC or FRC specific. Both the FTC Q&A and the FRC Q&A (https://frc-qa.firstinspires.org/) are the same website, more or less, so I'd really appreciate another argument or command to differentiate between the two program's Q&A websites.

**Comment by skruglov2023** [comment]
I can probably combine the 2 and make it /qa ftc and /qa frc, soon.

**Comment by tweirtx** [comment]
There is no existing command, but given that the software behind frc-qa and ftc-qa are the same, it should be easy to make one by just changing the URL in the lookup.

**Comment by skruglov2023** [comment]
I'll add it to the cog after AP exams

**Comment by skruglov2023** [comment]
Nevermind, I just did added frcqa now. 
https://imgur.com/a/ipDtoVw

**Review by tweirtx — APPROVED** [review]

**Review by JayFromProgramming — APPROVED** [review]

**Pull request merged**
