### PR TITLE
Feedback system

### PR DESCRIPTION
**Pull request by TomOrth**
-Feedback command with subcommand for configuration
-Works only from dm conversations so that it is anonymous
-Sends message as Embed
-Null checks galore so that the bot doesn't crash

### CODE REVIEW

**Comment by bkeeneykid** [comment]
On @endreman0's comments, you might want to use `fuzzywuzzy`'s built in `extractOne` method to automatically choose the one with the highest match.

**Comment by mcao** [comment]
Any update on this?

**Comment by atf1999** [comment]
No. Exams and stuff. Fall break is tomorrow for ~4 days. Will get the stuff done then

**Comment by tweirtx** [comment]
[Feedback system, similar to ModBot's mod mail system](https://trello.com/c/UafIwhYV/8-feedback-system-similar-to-modbots-mod-mail-system)

**Pull request closed without merging**
