### PR TITLE
Self deafens 

### PR DESCRIPTION
**Pull request by tweirtx**

### CODE REVIEW

**Comment by mcao** [comment]
I have two concerns:
- How will they execute the selfundeafen command if they're deafened?
- Wouldn't allowing them to self undeafen rather than putting in a timer defeat the command's purpose?

**Comment by tweirtx** [comment]
1. The selfdeafen command undeafens them in the channel it was called in
2. :shrug: idk

**Comment by tweirtx** [comment]
[self deafens, timed mutes/defeans](https://trello.com/c/3k278WjF/22-self-deafens-timed-mutes-defeans)

**Comment by tweirtx** [comment]
Code optimized, ready to be bashed in another review

**Comment by tweirtx** [comment]
More optimizing needed apparently, will be done soon

**Comment by tweirtx** [comment]
Ready for review

**Pull request merged**
