### PR TITLE
TBA Command with team and traw subgroups, and run.bat

### PR DESCRIPTION
**Pull request by 770352**
run.bat pulls GitHub code using git pull (If git installed and if in a git directory), updates requirements, and starts dozer with one button push and also holds the console open if dozer or python crashes

### CODE REVIEW

**Comment by bkeeneykid** [comment]
@770352 It justs sounds like you were too lazy to use a IDE so wrote a shell script instead. If that's how you want to run the bot, that's fine, just don't put it in the repo.

**Comment by tweirtx** [comment]
You can have the repo not pick it up by adding to the .gitignore file

**Comment by 770352** [comment]
@bkeeneykid Ok, I don't know how you want it done but that's how I do it. I will fix it in about a hour and 20 mins. (Leaving for school right now.)

**Comment by 770352** [comment]
Good to recheck

**Comment by mcao** [comment]
I'll conditionally accept these changes pending tbapi's move to API v3 and an expansion of the command when that happens (cough @bkeeneykid cough @endreman0)

**Comment by tweirtx** [comment]
I'll review in school, I don't have time to review right now.

**Pull request merged**
