### PR TITLE
Added non existent team handling in TBA

### PR DESCRIPTION
**Pull request by 770352**

### CODE REVIEW

**Comment by tweirtx** [comment]
[Fix TBA non-existent team handling](https://trello.com/c/1NdZrjnM/58-fix-tba-non-existent-team-handling)

**Comment by 770352** [comment]
I have added general error handling so if a TBA Dies or a Misconfiguration happens, It will just say that a fatal error occurred.

**Comment by 770352** [comment]
PUUUUSHED!

**Comment by 770352** [comment]
PUUUUUUUSHED

**Pull request merged**
