### PR TITLE
Make README.md more detailed

### PR DESCRIPTION
**Pull request by elevenchars**
Was having some trouble getting this to work, so I updated the readme with prerequisites that I needed to get the bot to work. Some distros (looking at you, Ubuntu 16.04) still do not have python 3.6+ in their official repos, so I think this would be good to clarify.

### CODE REVIEW

**Comment by elevenchars** [comment]
I went ahead and made the instructions more thorough through the whole document. The markdown editor I use seems  to litter those numbers everywhere, not sure how to fix that.

**Comment by elevenchars** [comment]
haven't had much time to work on this recently. i think this is ready to merge unless there is anything i missed.

**Comment by elevenchars** [comment]
how do i request changes again?

**Comment by tweirtx** [comment]
Reviews you mean? There should be a button to dismiss reviews

**Comment by mcao** [comment]
To request changes you have to be part of the organization I think. Then you can go to the changes tab, click on add review, and request changes.

**Comment by mcao** [comment]
To dismiss reviews there is a button

**Comment by elevenchars** [comment]
There is no option for me to dismiss reviews.

**Pull request merged**
