### PR TITLE
updated %toa to not actually use toa but work with a more up to date db

### PR DESCRIPTION
**Pull request by guineawheek**
This patch is cherrypicked from my development branch - see #dozer-development for more details

### CODE REVIEW

**Comment by 770352** [comment]
Why wouldn't we pull data from straight from TOA's API?

**Comment by guineawheek** [comment]
because TOA's reg data is often hilariously out of date and incomplete

**Comment by guineawheek** [comment]
@770352 because TOA's reg data is often hilariously out of date and incomplete

**Comment by tweirtx** [comment]
Seeing as TOA has fixed your complaint with them and a TOA developer is working on a fix to bring us up to date, I now see no reason for this PR.

**Pull request closed without merging**
