### PR TITLE
moved firstqa.py to correct folder

### PR DESCRIPTION
**Pull request by skruglov2023**
Previous PR that I added this, I accidentally added it to the top-level folder rather than cogs. Also, corrected FTC->FRC on one of the comments for frc qa

### CODE REVIEW

**Review by tweirtx — CHANGES_REQUESTED** [review]
Would prefer if the scraper was in a function that both of the commands called...lots of duplicate code.

**Review by tweirtx — DISMISSED** [review]

**Comment by skruglov2023** [comment]
Only issue pylint finds is the inability to find bs4 (BeautifulSoup), which is used to find the Q/A elements on the firstqna forums.

**Comment by guineawheek** [comment]
> Only issue pylint finds is the inability to find bs4 (BeautifulSoup), which is used to find the Q/A elements on the firstqna forums.

While we're at it, you should probably add beautifulsoup4 to the requirements.txt

**Comment by skruglov2023** [comment]
Finally got the thing to show up right, bs4 version was not right I guess? it passed this time

**Review by tweirtx — APPROVED** [review]

**Pull request merged**
