### PR TITLE
Updating nonexistent team handling

### PR DESCRIPTION
**Pull request by tweirtx**
The new version of TBApi handles nonexistent teams in a different way, so the nonexistent team handler has been updated to account for that

### CODE REVIEW

**Comment by tweirtx** [comment]
[TBA nonexistent team handling is broken and returns a weird error](https://trello.com/c/rSvkvO4S/65-tba-nonexistent-team-handling-is-broken-and-returns-a-weird-error)

**Comment by guineawheek** [comment]
should probably update namegame code with this too....

**Comment by tweirtx** [comment]
Will do

**Comment by tweirtx** [comment]
Done

**Comment by tweirtx** [comment]
Oops, missed the print statement. I'll take that out and make the other change shortly

**Comment by 770352** [comment]
Just saw this, Will update all TBA commands unless someone has already done that.

**Comment by tweirtx** [comment]
@770352 it's in the works, that's why this PR exists. Don't worry about it, I just need to fix how the error handling works

**Pull request merged**
